### ISSUE TITLE
Should be in error state if snap service down and uninstallation failed

### ISSUE THREAD

**Issue by Pjack** [canonical/openstack-exporter-operator#108]
Address the issue mentioned in 

* Snap service is down
  * https://github.com/canonical/openstack-exporter-operator/pull/100#discussion_r1758186715

* Un-installation failed
  * https://github.com/canonical/openstack-exporter-operator/pull/100#discussion_r1758175152
  * https://github.com/canonical/openstack-exporter-operator/pull/100#discussion_r1758179346

* Snap installtion failed (I found it additionally)
  * https://github.com/canonical/openstack-exporter-operator/blob/main/src/charm.py#L154

**Comment by Pjack** [comment]
After discussing with @jdkandersson, I believe we can adopt this practice in the GitHub runner. 
We don't set the charm to ErrorStatus; instead, we allow the exceptions to bubble up and be handled by the Ops framework.
https://github.com/canonical/github-runner-operator/blob/main/src/charm.py#L454

That's to say. If an unexpected error occurs in the workload (e.g., installation failure, service downtime), raise an exception in the charm if no specific action can be provided to resolve the issue. After the operator reviews the workload logs, they can manually resolve Juju. 

What do you think ?

**Comment by jneo8** [comment]
+1 for error status. It's a diverge situation so we can't provide a document or instruction to the user.
