### ISSUE TITLE
Alert on port in binding_failed 

### ISSUE THREAD

**Issue by peppepetra** [canonical/openstack-exporter-operator#112]
If a router failover while neutron is under heavy load, the failover may fail and the port is left in binding failed. This is reflected into openstack_neutron_port metric. It will be useful to have an alert when this happens.

Example metric:
```
openstack_neutron_port{admin_state_up="true", binding_vif_type="binding_failed", device_owner="network:router_gateway", fixed_ips="10.141.0.101,2620:2d:4002:1000::36d,", instance="10.140.11.49:9180", job="golang-prometheus-exporter", mac_address="fa:16:3e:73:39:d7", network_id="6fb849ea-7830-4ba9-bdee-aa7e7fd9166b", status="ACTIVE", uuid="04282d3c-0dc1-4a23-a828-ddf4ad336db1"}
```

**Comment by gabrielcocenza** [comment]
PR on sunbeam was opened. Once is merged there it will sync with this repo:

https://review.opendev.org/c/openstack/sunbeam-charms/+/932651
