### ISSUE TITLE
Changing VM Flavor breaks Grafana\OpenStack Compute Overview

### ISSUE THREAD

**Issue by mcfly722** [canonical/openstack-exporter-operator#120]
**Scenario:**
Start changing flavor for one of VMs in Openstack, but do not approve it.

![changing_flavor](https://github.com/user-attachments/assets/5bfcec8e-17d3-4ffc-8b20-d3be5fbeec30)

After that next views:

- Grafana\OpenStack Compute Overview\Instance Stats
- Grafana\OpenStack Compute Overview\CPU Time
- Grafana\OpenStack Compute Overview\Instance Memory Usage
- Grafana\OpenStack Compute Overview\Max Instance Memory
- Grafana\OpenStack Compute Overview\Instance Network Throughput
- Grafana\OpenStack Compute Overview\Instance Packet Rate
- Grafana\OpenStack Compute Overview\Instance Errors and Drops
- Grafana\OpenStack Compute Overview\IOPS Read
- Grafana\OpenStack Compute Overview\IOPS Write
- Grafana\OpenStack Compute Overview\Throughput Read
- Grafana\OpenStack Compute Overview\Throughput Write

becomes unavailable:

![changing_flavor_brokes Openstack_Compute_Grafana_Views](https://github.com/user-attachments/assets/86e64f3a-27f7-4f7c-9bf0-bbb76b740754)

with next error:
```
Status: 500. Message: execution: found duplicate series for the match group {domain="instance-00000529"} on the right hand-side of the operation:

[
	{
		__name__="libvirt_domain_info_meta",
		domain="instance-00000529",
		flavor="stdp1-16-64",
		instance="10.88.52.58:9177",
		instance_name="stdp1-16-64",
		job="juju_cos_87ebbcf_prometheus-scrape-target-k8s_external_jobs",
		project_name="test",
		project_uuid="2acbb68a827846b9a4660e747f1c24e2",
		user_name="test@local.domain",
		user_uuid="df27ae452dbe42c6a30d50a0e9c0e8c5",
		uuid="1b1aa990-94b5-404d-aef0-4b69c7c2f6ae"
	}, {
		__name__="libvirt_domain_info_meta",
		domain="instance-00000529",
		flavor="stdp1-8-32",
		instance="10.88.52.59:9177",
		instance_name="stdp1-16-64",
		job="juju_cos_87ebbcf_prometheus-scrape-target-k8s_external_jobs",
		project_name="test",
		project_uuid="2acbb68a827846b9a4660e747f1c24e2",
		user_name="test@local.domain",
		user_uuid="df27ae452dbe42c6a30d50a0e9c0e8c5",
		uuid="1b1aa990-94b5-404d-aef0-4b69c7c2f6ae"
	}
];

many-to-many matching not allowed: matching labels must be unique on one side
```

We guess it is because Openstack creates second VM instance and this instance visible with the same uuid.

Your grafana views in queries like:
```
rate(
	libvirt_domain_info_cpu_time_seconds_total{
		juju_application=~"$juju_application",
		juju_model=~"$juju_model",
		juju_model_uuid=~"$juju_model_uuid",
		juju_unit=~"$juju_unit"
	}[$__rate_interval]) * on(juju_unit, domain) group_left(project_name, instance_name, uuid) libvirt_domain_info_meta{
		juju_application=~"$juju_application",
		juju_model=~"$juju_model",
		juju_model_uuid=~"$juju_model_uuid",
		juju_unit=~"$juju_unit",
		project_name=~"$project"
	}
```
have grouping:
```
group_left(project_name, instance_name, uuid)
```
and for this two instances with same uuid there are no unique (project_name, instance_name, uuid) pair in this grouping.

We thinking that adding "flavor" field for this grouping will resolve this issue, but maybe there are a more suitable solution for this problem.

**Comment by chanchiwai-ray** [comment]
I think it's fine to include one more label to handle the "resize" case. @mcfly722 Does adding "flavor" worked for you?
