### ISSUE TITLE
Don't enter blocked status if grafana-agent not related

### ISSUE THREAD

**Issue by samuelallan72** [canonical/openstack-exporter-operator#45]
Currently if grafana-agent is not related the charm will be in blocked status.  Possibly this could be confusing.  We could consider leaving in active state (perhaps with a message in the status about relating to grafana-agent for dashboards and prometheus scraping).

To discuss.

Pros of staying blocked when no grafana-agent
- save resources while nothing is scraping
- can still shell in and start the snap service manually if you want for testing (I think)

Pros of changing to active when no grafana-agent
- it's confusing if it's blocked (it's not a blocking issue for the exporter technically)
- annoying if you want to manually test the metrics without connecting prometheus/grafana

**Comment by aieri** [comment]
I think setting blocked is good because it makes the charm self-validating, avoiding the need to write rules for juju-lint or juju-doctor

**Comment by samuelallan72** [comment]
That's a fair comment. If it makes it easier for operations, then let's keep it as is. :+1:

**Comment by aieri** [comment]
closing as won't do as we actually like the current behavior :)
