### ISSUE TITLE
Create a Project Usage dashboard

### ISSUE THREAD

**Issue by peppepetra** [canonical/openstack-exporter-operator#65]
This is to track the work needed to implement a dashboard that leveraging on the limits metrics give an overview on the resources utilized by a project in OpenStack.

Metrics used:

```
openstack_cinder_limits_backup_max_gb
openstack_cinder_limits_backup_used_gb
openstack_cinder_limits_volume_max_gb
openstack_cinder_limits_volume_used_gb
openstack_nova_limits_instances_max
openstack_nova_limits_instances_used
openstack_nova_limits_memory_max
openstack_nova_limits_memory_used
openstack_nova_limits_vcpus_max
openstack_nova_limits_vcpus_used
openstack_neutron_network_ip_availabilities_total
openstack_neutron_network_ip_availabilities_used
```

The dashboard will also list the VMs runnings on the project with some additional info like host, status, ephemeral storage used etc.

Screenshot 

![Screenshot from 2024-05-17 10-39-12](https://github.com/canonical/openstack-exporter-operator/assets/4116139/aee1599b-0c25-42a0-b3bb-6fba0431c8f0)

**Comment by chanchiwai-ray** [comment]
@samuelallan72 is this now fixed by https://github.com/canonical/openstack-exporter-operator/pull/67?

**Comment by samuelallan72** [comment]
Ah yes, it is, thanks @chanchiwai-ray :)
