### ISSUE TITLE
cacert should be a file path and not a string on cloud.yaml

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/openstack-exporter-operator#97]
Right now the cloud.yaml file is passing the cacert as a string which is not the standard way from the [documentation](https://docs.openstack.org/python-openstackclient/2024.1/configuration/index.html)

**Comment by chanchiwai-ray** [comment]
I suspect this indentation error, which I saw in [openstack-exporter-k8s](https://opendev.org/openstack/sunbeam-charms/commit/ca875b8dd13d9a1ed305844c6a39cdb3f0f2944b). The upstream documentation mentioned that it can be cacert string: https://github.com/openstack-exporter/openstack-exporter?tab=readme-ov-file#openstack-configuration

**Comment by aieri** [comment]
yes, but the idea here is that openstack-exporter should behave in the same way as any [openstack client](https://docs.openstack.org/python-openstackclient/latest/configuration/index.html), which indeed it does, save for a small difference: the cacert option can either be a string or a path to a file (for the exporter), but it can only be a path for python-openstackclient. We think the charm should try to use the exporter in the most default way possible, meaning that the clouds.yaml file it renders should pass a path to the CA cert, not a string (even if either would work).
